### ISSUE TITLE
Unable to install on FreeBSD

### ISSUE THREAD

**Issue by rosricard** [bnjmnp/pysoem#164]
I'm running python version 3.9.18 on a freeBSD OS.  I am unable to install pysoem on this platform. Worth noting the same venv setup on my Mac worked fine but I don't appear to be able to duplicate this on the FreeBSD OS. The first issue was that `freebsd` needed to be added to `soem_macros`:
```
Collecting pysoem
  Using cached pysoem-1.1.9.tar.gz (443 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "/usr/home/Administrator/code/white_rabbit/env/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/home/Administrator/code/white_rabbit/env/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/home/Administrator/code/white_rabbit/env/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-30khbths/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-30khbths/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-30khbths/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 37, in <module>
      NameError: name 'soem_macros' is not defined
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
I fixed this by cloning the library locally and updating the following line in `setup.py`:
```
elif sys.platform.startswith('linux' ) or sys.platform.startswith('freebsd'):

    soem_macros = []
    soem_lib_dirs = []
    soem_libs = ['pthread', 'rt']
    os_name = 'linux'
```

But unfortunately now it seems to be failing to build the SOEM sub module (gcc is installed and good to go). Pasted the output below in someone who knows more than I do has some suggestions.
```
(env) Administrator@CX-71D5E3:~/code/pysoem $ pip install -e .
Obtaining file:///usr/home/Administrator/code/pysoem
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Building wheels for collected packages: pysoem
  Building editable for pysoem (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building editable for pysoem (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [109 lines of output]
      running editable_wheel
      creating /tmp/pip-wheel-k45o_2op/.tmp-5e2jew9z/pysoem.egg-info
      writing /tmp/pip-wheel-k45o_2op/.tmp-5e2jew9z/pysoem.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-wheel-k45o_2op/.tmp-5e2jew9z/pysoem.egg-info/dependency_links.txt
      writing top-level names to /tmp/pip-wheel-k45o_2op/.tmp-5e2jew9z/pysoem.egg-info/top_level.txt
      writing manifest file '/tmp/pip-wheel-k45o_2op/.tmp-5e2jew9z/pysoem.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-wheel-k45o_2op/.tmp-5e2jew9z/pysoem.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file '/tmp/pip-wheel-k45o_2op/.tmp-5e2jew9z/pysoem.egg-info/SOURCES.txt'
      creating '/tmp/pip-wheel-k45o_2op/.tmp-5e2jew9z/pysoem-1.1.10.dist-info'
      creating /tmp/pip-wheel-k45o_2op/.tmp-5e2jew9z/pysoem-1.1.10.dist-info/WHEEL
      running build_py
      running build_ext
      building 'pysoem.pysoem' extension
      creating /tmp/tmpo3dfpclg.build-temp/soem/osal/linux
      creating /tmp/tmpo3dfpclg.build-temp/soem/oshw/linux
      creating /tmp/tmpo3dfpclg.build-temp/soem/soem
      creating /tmp/tmpo3dfpclg.build-temp/src/soem
      creating /tmp/tmpo3dfpclg.build-temp/src/pysoem
      cc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fcommon -fstack-protector-strong -fno-strict-aliasing -fPIC -DEC_VER2= -DUSE_SOEM_CONFIG_H= -I./pysoem -I./soem/oshw/linux -I./soem/osal/linux -I./soem/oshw -I./soem/osal -I./soem/soem -I./src/soem -I/usr/home/Administrator/code/white_rabbit/env/include -I/usr/local/include/python3.9 -c ./soem/osal/linux/osal.c -o /tmp/tmpo3dfpclg.build-temp/./soem/osal/linux/osal.o
      ./soem/osal/linux/osal.c:6:10: fatal error: time.h: No such file or directory
          6 | #include <time.h>
            |          ^~~~~~~~
      compilation terminated.
      Traceback (most recent call last):
        File "/tmp/pip-build-env-qbtaup5e/overlay/lib/python3.9/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
          subprocess.check_call(cmd, env=_inject_macos_ver(env))
        File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/local/bin/cc', '-pthread', '-Wno-unused-result', '-Wsign-compare', '-Wunreachable-code', '-DNDEBUG', '-O2', '-pipe', '-fcommon', '-fstack-protector-strong', '-fno-strict-aliasing', '-fPIC', '-DEC_VER2=', '-DUSE_SOEM_CONFIG_H=', '-I./pysoem', '-I./soem/oshw/linux', '-I./soem/osal/linux', '-I./soem/oshw', '-I./soem/osal', '-I./soem/soem', '-I./src/soem', '-I/usr/home/Administrator/code/white_rabbit/env/include', '-I/usr/local/include/python3.9', '-c', './soem/osal/linux/osal.c', '-o', '/tmp/tmpo3dfpclg.build-temp/./soem/osal/linux/osal.o']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/tmp/pip-build-env-qbtaup5e/overlay/lib/python3.9/site-packages/setuptools/_distutils/unixccompiler.py", line 200, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
        File "/tmp/pip-build-env-qbtaup5e/overlay/lib/python3.9/site-packages/setuptools/_distutils/ccompiler.py", line 1045, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/tmp/pip-build-env-qbtaup5e/overlay/lib/python3.9/site-packages/setuptools/_distutils/spawn.py", line 76, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command '/usr/local/bin/cc' failed with exit code 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/tmp/pip-build-env-qbtaup5e/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 139, in run
          self._create_wheel_file(bdist_wheel)
        File "/tmp/pip-build-env-qbtaup5e/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 340, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "/tmp/pip-build-env-qbtaup5e/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 263, in _run_build_commands
          self._run_build_subcommands()
        File "/tmp/pip-build-env-qbtaup5e/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 290, in _run_build_subcommands
          self.run_command(name)
        File "/tmp/pip-build-env-qbtaup5e/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-qbtaup5e/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-qbtaup5e/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-qbtaup5e/overlay/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 99, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-qbtaup5e/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/tmp/pip-build-env-qbtaup5e/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-qbtaup5e/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-build-env-qbtaup5e/overlay/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 264, in build_extension
          _build_ext.build_extension(self, ext)
        File "/tmp/pip-build-env-qbtaup5e/overlay/lib/python3.9/site-packages/Cython/Distutils/build_ext.py", line 135, in build_extension
          super(build_ext, self).build_extension(ext)
        File "/tmp/pip-build-env-qbtaup5e/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 557, in build_extension
          objects = self.compiler.compile(
        File "/tmp/pip-build-env-qbtaup5e/overlay/lib/python3.9/site-packages/setuptools/_distutils/ccompiler.py", line 606, in compile
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/tmp/pip-build-env-qbtaup5e/overlay/lib/python3.9/site-packages/setuptools/_distutils/unixccompiler.py", line 202, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/local/bin/cc' failed with exit code 1
      /tmp/pip-build-env-qbtaup5e/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py:973: _DebuggingTips: Problem in editable installation.
      !!
      
              ********************************************************************************
              An error happened while installing `pysoem` in editable mode.
      
              The following steps are recommended to help debug this problem:
      
              - Try to install the project normally, without using the editable mode.
                Does the error still persist?
                (If it does, try fixing the problem before attempting the editable mode).
              - If you are using binary extensions, make sure you have all OS-level
                dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
              - Try the latest version of setuptools (maybe the error was already fixed).
              - If you (or your project dependencies) are using any setuptools extension
                or customization, make sure they support the editable mode.
      
              After following the steps above, if the problem still persists and
              you think this is related to how setuptools handles editable installations,
              please submit a reproducible example
              (see https://stackoverflow.com/help/minimal-reproducible-example) to:
      
                  https://github.com/pypa/setuptools/issues
      
              See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
              ********************************************************************************
      
      !!
        cmd_obj.run()
      error: command '/usr/local/bin/cc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for pysoem
Failed to build pysoem
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pysoem)
```

**Comment by rosricard** [comment]
Looks like there are a lot of linux-isms in the SOEM C library so that entire library would need some work to be able to be ported over to a FreeBSD machine anyway.
